# Generated by Django 4.1 on 2022-09-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, verbose_name='Приватная запись'),
        ),
        migrations.AlterField(
            model_name='note',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
