# Generated by Django 4.1 on 2022-09-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_note_hidden_alter_note_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='hidden',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Приватная запись'),
        ),
    ]
